apiVersion: v1
kind: Namespace
metadata:
  name: paris

---
apiVersion: v1
kind: Pod
metadata:
  name: cat
  namespace: paris
  labels:
    animal: cat
    breed: sphynx
spec:
  containers:
  - image: jvassev/animal-logger
    imagePullPolicy: Always
    name: main
    env:
    - name: ANIMAL
      value: cat 
    - name: SOUND
      value: miaou
  volumes:
  - name: logs
    emptyDir: {}
