apiVersion: v1
kind: Namespace
metadata:
  name: london

---
apiVersion: v1
kind: Pod
metadata:
  name: cat
  namespace: london
  labels:
    animal: cat
    breed: munchkin
spec:
  containers:
  - image: jvassev/animal-logger
    imagePullPolicy: Always
    name: main
    env:
    - name: ANIMAL
      value: cat 
    - name: SOUND
      value: meow
  volumes:
  - name: logs
    emptyDir: {}
