#!./inject-secrets.sh
apiVersion: v1
kind: Namespace
metadata:
  name: paris

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: paris
data:
  fluent.conf: |
    <match **>
      @type loggly
      loggly_url https://logs-01.loggly.com/inputs/$LOGGLY_TOKEN/tag/fluentd
    </match>
    # <match **>
    #   @type elasticsearch
    #   include_tag_key false
    #   host "cloud.humio.com"
    #   path "/api/v1/dataspaces/sandbox/ingest/elasticsearch/"
    #   scheme "https"
    #   port "443"
    #   user "$HUMIO_KEY"
    #   password ""
    #   logstash_format true
    #   reload_connections "true"
    #   logstash_prefix "fluentd:kubernetes2humio"
    #   buffer_chunk_limit 1M
    #   buffer_queue_limit 32
    #   flush_interval 1s
    #   max_retry_wait 30
    #   disable_retry_limit
    #   num_threads 8
    # </match>
