#!./inject-secrets.sh
apiVersion: v1
kind: Namespace
metadata:
  name: london

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: london
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/logs/dogd.log
      labels animal=dog, _container=main
      <parse>
        #@type json
        @type none
      </parse>
    </source>

    <match kube.paris.**>
      @type loggly
      loggly_url https://logs-01.loggly.com/inputs/$LOGGLY_TOKEN/tag/fluentd
    </match>
