apiVersion: v1
kind: Namespace
metadata:
  name: london

---
apiVersion: v1
kind: Pod
metadata:
  name: dog
  namespace: london
  labels:
    animal: dog
    breed: pug
spec:
  containers:
  - image: jvassev/animal-logger
    imagePullPolicy: Always
    name: main
    env:
    - name: ANIMAL
      value: dog 
    - name: SOUND
      value: bark-bark
    - name: FILE
      value: /var/logs/dogd.log
    volumeMounts:
    - name: logs
      mountPath: /var/logs
  volumes:
  - name: logs
    emptyDir: {}
